USE [master]
GO

/****** Object:  Database [Coarev]    Script Date: 2022-09-22 20:38:43 ******/
CREATE DATABASE [Coarev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Coarev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Coarev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Coarev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Coarev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Coarev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Coarev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Coarev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Coarev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Coarev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Coarev] SET ARITHABORT OFF 
GO

ALTER DATABASE [Coarev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Coarev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Coarev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Coarev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Coarev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Coarev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Coarev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Coarev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Coarev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Coarev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Coarev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Coarev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Coarev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Coarev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Coarev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Coarev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Coarev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Coarev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Coarev] SET  MULTI_USER 
GO

ALTER DATABASE [Coarev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Coarev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Coarev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Coarev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Coarev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Coarev] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Coarev] SET  READ_WRITE 
GO

-------------------------------------------------------------------------------------------------

USE [Coarev]
GO
/****** Object:  Table [dbo].[Actions]    Script Date: 2022-09-22 20:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actions](
	[Id] [int] NOT NULL,
	[ActionDesc] [nvarchar](256) NOT NULL,
	[TrackTypesId] [int] NOT NULL,
	[Quantity] [numeric](10, 2) NULL,
	[UnitiesId] [int] NOT NULL,
	[Duration] [time](7) NULL,
	[TagList] [nvarchar](max) NULL,
	[IsArchived] [bit] NOT NULL,
	[UsersId] [int] NOT NULL,
 CONSTRAINT [PK_Actions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tags]    Script Date: 2022-09-22 20:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tags](
	[Id] [int] NOT NULL,
	[TagDesc] [nvarchar](50) NOT NULL,
	[UsersId] [int] NOT NULL,
 CONSTRAINT [PK_Tags] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tracks]    Script Date: 2022-09-22 20:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tracks](
	[Id] [int] NOT NULL,
	[ActionsId] [int] NOT NULL,
	[StartAt] [datetime] NOT NULL,
	[EndAt] [datetime] NULL,
	[Quantity] [numeric](10, 2) NULL,
	[TagList] [nvarchar](max) NULL,
	[Notes] [nvarchar](max) NULL,
 CONSTRAINT [PK_Tracks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TrackTypes]    Script Date: 2022-09-22 20:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TrackTypes](
	[Id] [int] NOT NULL,
	[TrackTypeDesc] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TrackTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Unities]    Script Date: 2022-09-22 20:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Unities](
	[Id] [int] NOT NULL,
	[UnityDesc] [nvarchar](50) NOT NULL,
	[UsersId] [int] NOT NULL,
 CONSTRAINT [PK_Unities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 2022-09-22 20:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] NOT NULL,
	[Alias] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Actions] ADD  CONSTRAINT [DF_Actions_IsArchived]  DEFAULT ((0)) FOR [IsArchived]
GO

